### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by cottsay** [vcstools/rosinstall_tab_completion#1]
Does this tool still work with current `rosinstall`?

If so, could someone tag a release so this tool can be packaged?

Thanks,

--scott

**Comment by tkruse** [comment]
Yes, the tab completion should work. So +1

**Comment by cottsay** [comment]
I just came here to open this exact issue, only to discover I already opened it 4 years ago :P

Any chance someone with commit access can bump the package to `0.0.2`?

Also, `rosinstall` has had some churn since 2012. Does this package need to be re-aligned?

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #3.
